use_frameworks!

target 'SQDifferenceKit_Example' do
  project './SQDifferenceKit - Cocoapods.xcodeproj'
  pod 'SQDifferenceKit', :path => '../'

  target 'SQDifferenceKit_Tests' do
    inherit! :search_paths

    
  end
end
